### ISSUE TITLE
Automatically include subdirectories of src/main/avro

### ISSUE THREAD

**Issue by tsnee** [commercehub-oss/gradle-avro-plugin#11]
The plugin works beautifully with one schema file in src/main/avro. If I wanted to work with several schema files, it would be nice to organize them in separate subdirectories, for instance, src/main/avro/foo, src/main/avro/bar, etc. Unfortunately, the plugin seems to ignore files that are not direct children of src/main/avro. Could that be changed?

**Comment by davidmc24** [comment]
This should be possible to support. In fact, I would have thought it was already supported, though I personally haven't needed it yet. Pull requests welcome, or I'll get to it myself at some point.

**Comment by jamesbassett** [comment]
We do this (organize schemas into subdirectories) with the following gradle config:

    task generateAvro(type: com.commercehub.gradle.plugin.avro.GenerateAvroJavaTask) {
        source("src/main/avro")
        include("**/*.avsc")
    }

**Comment by davidmc24** [comment]
Thanks for the pointer, @jamesbassett.  Version 0.4.1 will include this as the default behavior.
