### ISSUE TITLE
Support 2 schema with 1 POJO

### ISSUE THREAD

**Issue by hatavan83** [commercehub-oss/gradle-avro-plugin#13]
I have a problem with version 0.3.4, when I generate POJO class from 2 schema, if two schema reference the same POJO class, the same name in the same package, it will throw exception "SchemaParseException: Can't redefine ..."

**Comment by davidmc24** [comment]
I'm not sure that I'm understanding the situation.  Can you provide more details, or even better, an example project that reproduces the problem?

**Comment by gavinhogan** [comment]
@hatavan83 if you can, please add more information as request. If you fixed the problem yourself please add your solution for others to follow.  

If nothing more is added this week we will close the issue. 
Thanks

**Comment by hatavan83** [comment]
Ex schema:
{
    "type" : "record",
    "name" : "event",
    "namespace" : "my.example",
    "fields" : [{"name" : "id", 
                 "type" : "long", 
                 "default" : "NONE"}, 
  
                  {"name" : "program", 
                     "type" : {
                         "type" : "record",
                         "name" : "program",
                         "fields" : [
                            {"name" : "id", 
                             "type" : "long", 
                             "default" : "NONE"},

                            {"name" : "name", 
                             "type" : "string", 
                             "default" : "NONE"}
                            ]}
                }
    ]
} 

{
    "type" : "record",
    "name" : "categrory",
    "namespace" : "my.example",
    "fields" : [{"name" : "id", 
                 "type" : "long", 
                 "default" : "NONE"}, 
  
                  {"name" : "program", 
                     "type" : {
                         "type" : "record",
                         "name" : "program",
                         "fields" : [
                            {"name" : "id", 
                             "type" : "long", 
                             "default" : "NONE"},

                            {"name" : "name", 
                             "type" : "string", 
                             "default" : "NONE"}
                            ]}
                }
    ]
} 
 The plugin will throw error when I generate POJO from the folder contain 2 schema similar above, Event schema and Category schema contain the same record as Program class

**Comment by davidmc24** [comment]
I believe this will work fine with the plugin as-is if, instead of defining the "program" type inline, you pull it out into its own .avsc file.  I've re-worked your example to demonstrate that behavior in this gist.  The avro files go in src/main/avro.

https://gist.github.com/davidmc24/09c5938806d6b52c1fcc

**Comment by hatavan83** [comment]
My project is transform dynamic xml data to avro files. I receive xsd and Pojo class from another project, then I base on Pojo class to generate dynamic avsc files by the library  https://github.com/FasterXML/jackson-dataformat-avro.  After that I generate avro Pojo class based on avsc, so that I cannot change avsc manual. I can work successfully with another plug in, but with this one, it throw error :)

**Comment by davidmc24** [comment]
If, in your example, the "program" schema definition was different in the two files, what should the behavior be?  Using one and ignoring the other seems like an incorrect result (and likely surprising, as the choice of which one to use would be rather arbitrary from the user's perspective).  It isn't possible to use both without changing the class name of at least one, which would also be introducing behavior that the user would have no reason to expect.

We could having special-case support for the case where inline sub-schemas have redundant identical definitions.  However, this logic would add complexity and make the Java generation slower.  In `GenerateAvroJavaTask.processSchemaFiles`, we'd catch `SchemaParseException`s with a message like "Can't redefine: my.example.program", save a copy of the conflicting sub-schema from `types` to the side, retry compiling the file, and if it succeeds, check that the new version of the sub-schema matches the old version (and if not, fail the build).  I suppose we could make this an optional behavior, but the more configuration flags we add, the harder the plugin is to use.

In general, I think it's better to store re-used schemas as their own files.  It avoids these edge cases.  Perhaps you could adjust your avsc generation process to do so?

Out of curiosity, which other plugin is it that you say works with these duplicate sub-schemas?  My suspicion is that they are doing the Java generation of each file using a fresh `Schema.Parser`, meaning that most likely in your case the file `my/example/program.java` is being written multiple times, and if one of the definitions were different, it would be undefined which one "won".

**Comment by davidmc24** [comment]
Implemented support for this, will be included in the 0.7.0 release.
