### ISSUE TITLE
Enum complex type is not supported in the Avro schema definition

### ISSUE THREAD

**Issue by evarga** [commercehub-oss/gradle-avro-plugin#14]
The latest (0.4.0 version) Gradle Avro plugin seems to have problems with the 'enum' complex type in Avro schema. It throws a Gradle exception in the following part of the code:

    if (!nextPass.isEmpty()) {
        throw new GradleException(String.format("Failed to compile schema definition files due to       
        undefined names: %s", nextPass));
    }

**Comment by davidmc24** [comment]
I'm sorry to hear that you're having difficulty with the plugin.  I've added functional test coverage for enum handling to the automated test suite, and wasn't successful in reproducing this issue.  Can you provide a set of schema files that demonstrates the failure?

https://github.com/commercehub-oss/gradle-avro-plugin/blob/master/src/test/groovy/com/commercehub/gradle/plugin/avro/EnumHandlingFunctionalSpec.groovy

**Comment by evarga** [comment]
Here is the modified example file from your distribution.

    {
     "namespace": "example.avro",
     "type": "record",
     "name": "User",
     "fields": [
         {"name": "name", "type": "string"},
         {"name": "kind",  "type": "enum", "symbols" : ["ONE", "TWO", "THREE"]}
     ]
   }

It seems that the 'symbols' is not supported. Here is the link to the Avro spec.: <a href="http://avro.apache.org/docs/current/spec.html#schema_complex">http://avro.apache.org/docs/current/spec.html#schema_complex</a>

**Comment by evarga** [comment]
Here is the modified example file from your distribution.

    {
     "namespace": "example.avro",
     "type": "record",
     "name": "User",
     "fields": [
         {"name": "name", "type": "string"},
         {"name": "kind",  "type": "enum", "symbols" : ["ONE", "TWO", "THREE"]}
     ]
   }

It seems that the 'symbols' is not supported. Here is the link to the Avro spec.: <a href="http://avro.apache.org/docs/current/spec.html#schema_complex">http://avro.apache.org/docs/current/spec.html#schema_complex</a>

**Comment by davidmc24** [comment]
The test coverage I added this morning includes `symbols`, such as in [this file](https://github.com/commercehub-oss/gradle-avro-plugin/blob/master/src/test/resources/com/commercehub/gradle/plugin/avro/simpleEnum.avsc).

However, thanks to your example, I'm now able to reproduce the failure.  As far as I an tell, it doesn't affect enums defined in their own schema file (which can then be referenced from other schema files) or enums defined within a union.  So far, it looks like it's only affecting enums defined directly in a field definition.  I'm investigating whether this may be an upstream bug in `avro-compiler`.

**Comment by davidmc24** [comment]
Pretty sure I figured out the problem.  Your syntax is incorrect.  Instead of

```json
{
  "namespace": "example.avro",
  "type": "record",
  "name": "User",
  "fields": [
    {"name": "name", "type": "string"},
    {"name": "kind", "type": "enum", "symbols" : ["ONE", "TWO", "THREE"]}
  ]
}
```

you need

```json
{
  "namespace": "example.avro",
  "type": "record",
  "name": "User",
  "fields": [
    {"name": "name", "type": "string"},
    {
      "name": "kind",
      "type": {
        "name": "Kind",
        "type": "enum",
        "symbols" : ["ONE", "TWO", "THREE"]
      }
    }
  ]
}
```

The error message given by `avro-compiler` was:

    "enum" is not a defined name. The type of the "kind" field must be a defined name or a {"type": ...} expression.

I'm going to pursue some changes to the plugin to make errors thrown by the compiler more visible to aid in troubleshooting this type of issue.

**Comment by evarga** [comment]
Thanks a lot! At any rate, I fully agree that a more helpful error message would be much appreciated.

**Comment by davidmc24** [comment]
@evarga Please try version 0.5.0 when you have a chance.

**Comment by evarga** [comment]
I have just gave it a try, and it works perfectly! Thanks again!

**Comment by ekozynin** [comment]
According to Avro 1.10.2 (https://avro.apache.org/docs/current/spec.html#Enums), the below should be supported, however it fails with the same error message:

`"enum" is not a defined name. The type of the "type" field must be a defined name or a {"type": ...} expression.`

```json
{
  "type": "enum",
  "name": "Suit",
  "symbols" : ["SPADES", "HEARTS", "DIAMONDS", "CLUBS"]
}
```
