### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by ryonday** [commercehub-oss/gradle-avro-plugin#17]
Hi there David! I was wondering what further work/testing was required in order to issue a new release with the two features that I issued pull requests for; I would very much like to leverage them in my project!

I would be more than happy to share the workload required to get it there!

**Comment by davidmc24** [comment]
Nothing special required. I'll push a release tomorrow.

**Comment by ryonday** [comment]
Fantastic, thanks so much, and thanks for this project!

**Comment by davidmc24** [comment]
Version 0.6.0 released to Gradle plugin portal.
