### ISSUE TITLE
Android compatibility

### ISSUE THREAD

**Issue by mpj** [commercehub-oss/gradle-avro-plugin#22]
When I try to use this in an Android project, I get this error:
Error:The 'java' plugin has been applied, but it is not compatible with the Android plugins.

It seems like others have this problem with other packages: 
http://stackoverflow.com/questions/27454569/android-studio-gradle-and-plug-in-error

Can I use this plugin in an Android project at all? If so, how?

**Comment by davidmc24** [comment]
In the readme, see the Alternate Usage section. The main plugin applies the Java plugin and depends on it, while the base plugin does not. I don't do any android development, so I may not be able to help much more than that.

**Comment by mpj** [comment]
@davidmc24 thanks!

**Comment by davidmc24** [comment]
@mpj Any luck with getting it working?  If so, I'd be interested in hearing about it, so that we can improve the plugin's documentation to be more useful.

**Comment by davidmc24** [comment]
Closing due to lack of further response.
