### ISSUE TITLE
Support Avro 1.8 from Avro 1.7.7

### ISSUE THREAD

**Issue by Hydrotoast** [commercehub-oss/gradle-avro-plugin#23]
Could we support Avro 1.8 for generating class files that implement the `java.io.Serializable` interface? This is important for libraries such as Apache Spark for serializing objects into closures across a network. Functionality was added to Spark 1.7 via https://issues.apache.org/jira/browse/AVRO-1502.

**Comment by davidmc24** [comment]
Sure, we can upgrade the Avro version compatibility. Are you interested in contributing a pull request?

**Comment by benmccann** [comment]
PR here: https://github.com/commercehub-oss/gradle-avro-plugin/pull/24

**Comment by davidmc24** [comment]
Thanks for the PR.  I'll take a closer look at it, and if everything looks good, should be able to push out a release tomorrow or so.

**Comment by davidmc24** [comment]
Looks good.  Wanted to do some additional cross-version testing prior to release, which is now looking like Thursday or Friday.

**Comment by davidmc24** [comment]
Included in version 0.9.0

**Comment by Hydrotoast** [comment]
Cool. Thanks @benmccann and @davidmc24.
