### ISSUE TITLE
Cannot import Avro into a Gradle project in IntelliJ

### ISSUE THREAD

**Issue by fishercoder1534** [commercehub-oss/gradle-avro-plugin#29]
I have a Gradle project in my IntelliJ, I followed this [tutorial](https://plugins.gradle.org/plugin/com.commercehub.gradle.plugin.avro) in my build.gradle![build.gradle](https://i.imgsafe.org/9424994f6b.jpeg), but IntelliJ doesn't auto pop up Avro as an option:
![Avro not imported](https://i.imgsafe.org/9418c3681d.png)

And when I try to manually add this import ![line](https://i.imgsafe.org/942bcc9978.jpeg), it doesn't auto complete Avro as an option either.

Actually, I searched extensively online and tried different approaches, but still no luck, any ideas please?

Thanks a lot!

I asked the same [question](http://stackoverflow.com/questions/41864180/cannot-import-avro-into-a-gradle-project-in-intellij) on Stackoverflow. 

I'd really appreciate if someone could give me some insight.

Thanks!

**Comment by davidmc24** [comment]
As per the documentation (here: https://github.com/commercehub-oss/gradle-avro-plugin), this plugin doesn't automatically add a project dependency on avro for you; you need to do that yourself.    That allows you to control the version of Avro used in your project.  The relevant segment from the README is:

```
repositories {
    jcenter()
}
dependencies {
    compile "org.apache.avro:avro:1.8.1"
}
```

**Comment by fishercoder1534** [comment]
Thanks for your reply. But adding
```
plugins {
	id "com.commercehub.gradle.plugin.avro" version "0.9.0"
}
dependencies {
compile group: 'org.apache.avro', name: 'avro', version: '1.8.1'
}
```
resolved my issue.
Thanks anyway.
