### ISSUE TITLE
A cannot be cast to org.apache.avro.generic.IndexedRecord

### ISSUE THREAD

**Issue by fishercoder1534** [commercehub-oss/gradle-avro-plugin#30]
Sorry to creating an issue here. But I'm really confused where/which part I did wrong, so asking the authors of this open source project might be the best. :) And it might benefit other future clients who might run into the same issue. Thanks in advance.

Here's my .avdl file:

```

    @namespace("com.abc.xyz")
    protocol XYZ_Protocol_v1 {
      record VendorItemInfo {
          string vendorItemId;
          long price;
          string deliveryChargeType;
      }
    
      record XyzDto {
        array<VendorItemInfo> vendorItemInfos;
      }
    }

```

Based on commercehub-oss [wiki](https://github.com/commercehub-oss/gradle-avro-plugin), I ran $gradle build to generate the java files based on my .avdl file.
The Java classes were generated fine.

Then when I made a request to my service, I got this error stacktrace:
```
java.lang.ClassCastException: com.abc.xyz.domain.dto.VendorItemInfo cannot be cast to org.apache.avro.generic.IndexedRecord
	org.apache.avro.generic.GenericData.getField(GenericData.java:666)
	org.apache.avro.generic.GenericData.getField(GenericData.java:681)
	org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:151)
	org.apache.avro.specific.SpecificDatumWriter.writeField(SpecificDatumWriter.java:90)
	org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:143)
	org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:105)
	org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:73)
	org.apache.avro.generic.GenericDatumWriter.writeArray(GenericDatumWriter.java:179)
	org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:107)
	org.apache.avro.specific.SpecificDatumWriter.writeField(SpecificDatumWriter.java:87)
	org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:143)
	org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:105)
	org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:73)
	org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:60)
```

Any ideas how to fix this or where I did wrong please.

Thanks a lot.

**Comment by davidmc24** [comment]
You might be hitting https://issues.apache.org/jira/plugins/servlet/mobile#issue/AVRO-1810. I'll investigate more on Monday.

**Comment by davidmc24** [comment]
Information about what code you're calling when you get the error would be helpful.

**Comment by fishercoder1534** [comment]
@davidmc24 Thanks for your quick response.
Do you mean my code?
If so, here it is how I'm using the plugin generated Java class:
```
public static byte[] xyzServiceToByteArray(XyzDto xyzDto) {
		ByteArrayOutputStream stream = new ByteArrayOutputStream();
		try (ObjectOutput output = new ObjectOutputStream(stream)
		) {
			xyzDto.writeExternal(output);
		} catch (IOException e) {
			throw new CoupangRuntimeException(e);
		}
		return stream.toByteArray();
	}
```

And in my XyzDto.java class, it's this code segment that's throwing the error:
```
@Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }
```

Let me know if you need anything else.

**Comment by davidmc24** [comment]
When I use the provided `xyzServiceToByteArray` method and .avdl file, no exception results.  My current best guess is that you may have conflicting classloaders, such that VendorItemInfo was loaded from one classloader and IndexedRecord (and likely much of avro) was loaded from a different classloader, resulting in it not being not being castable.  Regardless, I recommend trying to isolate the failure in a smaller reproducible project to narrow down the cause.

**Comment by fishercoder1534** [comment]
Thanks @davidmc24  for the advice. I created a [Gradle project](https://github.com/fishercoder1534/AvroExample) and the same code works on my end as well.
And after that, I've created a new workspace on my machine, and then added the same code fragment little by little, now it seems to be working now.
Thanks for the help! ^ ^
