### ISSUE TITLE
0.9.1 not in Gradle plugin portal

### ISSUE THREAD

**Issue by tlberglund** [commercehub-oss/gradle-avro-plugin#33]
The [Gradle plugin portal](https://plugins.gradle.org/plugin/com.commercehub.gradle.plugin.avro) shows 0.9.1 as the latest version of the plugin, but apparently [0.3.4 is the latest version](https://jcenter.bintray.com/com/commercehub/gradle/plugin/gradle-avro-plugin/).

[This `build.gradle`](https://github.com/tlberglund/streams-movie-demo/blob/gradle-avro/build.gradle) (still under development) produces this error:

```~/code/kafka-streams-demo (master ✘)✹ ᐅ gradlew

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'kafka-streams-demo'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.commercehub.gradle.plugin:gradle-avro-plugin:0.9.1.
     Searched in the following locations:
         https://plugins.gradle.org/m2/com/commercehub/gradle/plugin/gradle-avro-plugin/0.9.1/gradle-avro-plugin-0.9.1.pom
         https://plugins.gradle.org/m2/com/commercehub/gradle/plugin/gradle-avro-plugin/0.9.1/gradle-avro-plugin-0.9.1.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

Is 0.9.1 out there anywhere? :)

**Comment by davidmc24** [comment]
0.10.0 is actually the latest, and is published to JCenter, as will future versions. I believe that 0.9.1 is correctly published to the plugin portal, but I'll check once I get back from vacation on October 10.

**Comment by tlberglund** [comment]
Awesome, enjoy your time off. I can't seem to build with 0.10.0 either, so I _think_ there's a problem with what's in the portal, but we'll get this figured out when you get back. I currently have it working with a Maven build for the Avro stuff and Gradle for everything else, so it is not a huge hurry (other than wanting to expunge the `pom.xml` from my repo as anyone might).

**Comment by davidmc24** [comment]
Looks like 0.9.1 is broken due to a plugin portal issue; submitted https://discuss.gradle.org/t/gradle-avro-plugin-0-9-1-missing-artifacts/24423 to attempt to address.

**Comment by davidmc24** [comment]
https://github.com/tlberglund/streams-movie-demo/pull/1 has what appears to be a working example of using version 0.10.0

**Comment by timyates** [comment]
0.9.1 was broken in the Plugin portal (due to a bug we had with the publishing plugin)

I've removed 0.9.1 from the portal, so you should be ok to publish this, or a later version.

I have checked, and 0.9.0 is ok and has the expected artifacts

**Comment by davidmc24** [comment]
0.9.1 has been re-published to the plugin portal, and I've verified with a test project that it now appears to be resolvable.

**Comment by tlberglund** [comment]
Works for me now as well. Thank you!

**Comment by mykolapolonskyi** [comment]
@davidmc24  - can this one be reopened - seems that https://plugins.gradle.org/plugin/com.commercehub.gradle.plugin.avro contains out-of-dated version

**Comment by mhurne** [comment]
@mykolapolonskyi Per @davidmc24 's comment on Oct 4, 2017, releases are now published to [JCenter](https://bintray.com/commercehub-oss/main/gradle-avro-plugin) rather than the Gradle plugin portal. Per [CHANGES.md](https://github.com/commercehub-oss/gradle-avro-plugin/blob/fb7849dcf944f02c0d8092dd682a5917adf20997/CHANGES.md), 0.9.1 was the last version published to the Gradle plugin portal. I believe the Usage section of the README does show how to pull versions > 0.9.1 into a Gradle project. Here's the most trivial working example project I could come up with: https://github.com/mhurne/gradle-avro-plugin-test

**Comment by mykolapolonskyi** [comment]
@mhurne hi
And now - I`m fully confused - maybe was wrong completely misunderstand this block `Alternatively, if you prefer to use the **incubating** plugins DSL, see the following example:` - I`m using kotlins dsl and I should use this block firs of all. but I thought that this block is for use snapshots repo. 
my miss, probably, tnx for help!

**Comment by mhurne** [comment]
I see - the statement "Alternatively, if you prefer to use the **incubating** plugins DSL, see the following example" is referring to Gradle's plugins DSL which is in incubating, not an incubating feature of gradle-avro-plugin.
