### ISSUE TITLE
Support enableDecimalLogicalType compiler flag

### ISSUE THREAD

**Issue by eshepelyuk** [commercehub-oss/gradle-avro-plugin#34]
Avro 1.8.2 introduced `enableDecimalLogicalType` flag into complier that allows generating `BigDecimal` properties for fields annotated with `logicalType = decimal` (instead of current behaviour of generating `ByteBuffer` fields.

I'd like to create a PR for this feature, also upgrading AVRO to 1.8.2.

Any feedback is appreciated.

**Comment by davidmc24** [comment]
Thanks for the interest in the plugin.  Such a pull request is welcome, and would be very much appreciated.  I hadn't been aware of the new `setEnableDecimalLogicalType` method on `SpecificCompiler`, but it does indeed look like something appropriate to include support for.

I had previously attempted an upgrade to Avro 1.8.2, and hadn't moved forward with it yet as it looks like this will need to be a version where we break backwards-compatibility.  The Java files generated by Avro 1.8.2 require a class `org.apache.avro.message.BinaryMessageEncoder` which isn't present in previous versions of Avro.  I had been considering trying to make progress on my plan to decouple the version of Avro used by the plugin to the version of Avro used at build project compilation time (see `design-docs/run-avro-as-an-external-process.md` in this repo), but that's pretty involved and I'm unlikely to have time to work on that for a while.  Thus, it makes sense to move forward with the lighter-weight but compatibility-breaking upgrade approach for now.

A few tips:

* Performing the upgrade requires setting `compileAvroVersion` in `build.gradle`
* Removing backwards compatibility requires updating `avroVersions` in `build.gradle` and updating the compatibility notes in `README.md`
* The new flag is going to need test coverage in `OptionsFunctionalSpec` and documentation in `README.md`
* Please add notes for all changes (new flag, avro upgrade, avro compatibility change) to the "Unreleased" section of `CHANGES.md`; I'll deal with assigning a version number as part of the release process when we get there.

**Comment by eshepelyuk** [comment]
Hi, 
I've experienced the compatibility issue already while running tests.
So, did I get your words properly - as soon as we move to `1.8.2` there will be no compatibility check in `build.gradle` ?

**Comment by davidmc24** [comment]
Not quite. There will still be compatibility checking, both with versions of Avro and Gradle. We'll just reset the minimum version of Avro required for the plugin to 1.8.2. When Avro 1.8.3 or 1.9.0 comes out, hopefully they'll be cross-compatible and we would then leverage the same support for testing compatibility.

**Comment by eshepelyuk** [comment]
PR is added, plz feedback.

**Comment by davidmc24** [comment]
Released as 0.11.0.  Thanks again for the pull request, @eshepelyuk.
