### ISSUE TITLE
Help to generate to Kotlin file?

### ISSUE THREAD

**Issue by debop** [commercehub-oss/gradle-avro-plugin#37]
Hi, Thanks your plugin.

I saw prototype features for Kotlin in 0.12.1-SNAPSHOT. It awesome to me.
How to use this feature? Please some description.

**Comment by davidmc24** [comment]
The Kotlin is actually present in the 0.12.0 release version.  I've updated the README to describe how this feature works.  Feel free to re-open this issue if you still have questions after reading the new documentation section.
