### ISSUE TITLE
Support similar solution as AVRO-1642

### ISSUE THREAD

**Issue by AlexChenSkyBlue** [commercehub-oss/gradle-avro-plugin#38]
Right now. if the avro schema contain too many field,  Java will complain  error: code too large for the builder function. We have to manually delete builder class in these cases. It will be helpful to have a option to turn off generating two builder function.

**Comment by davidmc24** [comment]
My understanding of the history of https://issues.apache.org/jira/plugins/servlet/mobile#issue/AVRO-1642 is that the Avro compiler was enhanced to not generate the all argument constructor above a certain limit. If that's the case, it can be used with this plugin simply by using the appropriate version of Avro as part of the compilation process. If 1.8.2 contains the enhancement, the latest version of this plugin should already work. If you're looking for a different behavior that the compiler doesn't expose as an option, you'll need to get that included upstream in the Avro project before I'm able to do anything about it.

**Comment by AlexChenSkyBlue** [comment]
I see the issue is because of builder() function. No invalid constructor has been generated.  I will open a issue in Avro project to discuss that.
