### ISSUE TITLE
How to use "new" gradle plugin method

### ISSUE THREAD

**Issue by ryonday** [commercehub-oss/gradle-avro-plugin#40]
Not sure if you're interested in putting an ["incubating" Gradle feature](https://docs.gradle.org/4.4/userguide/plugins.html#sec:plugin_management) in your instructions (otherwise I would have opened a PR for the documentation), but I figured out how to use newer non-gradle-portal plugin versions with the new plugin declaration format. If you'd like, I'm more than happy to open a PR!

`settings.gradle`:
```
pluginManagement {
    repositories {
        gradlePluginPortal()
        jcenter()
        maven {
            name "JCenter Gradle Plugins"
            url  "https://dl.bintray.com/gradle/gradle-plugins"
        }
    }
}

include 'myCoolProject'
```

`build.gradle`
```
plugins {
    id 'com.commercehub.gradle.plugin.avro' version '0.12.0' apply false
}
.
.
.
project(':myCoolProject') {
    apply plugin: 'java'
    apply plugin: 'com.commercehub.gradle.plugin.avro'

    avro {
        stringType = 'string'
    }

dependencies {
        compile 'org.apache.avro:avro:1.8.2'
    }
}
```

Edit: Link to Gradle docs for the `pluginManagement` feature

**Comment by davidmc24** [comment]
Interesting.  When I moved this plugin back to Bintray, I tried to get it working in the old way with the incubating plugin syntax, but wasn't able to.  The additional pluginManagement repository you listed does indeed appear to work.  I'll add it to the documentation.  Thanks for pointing that out!  😸

**Comment by ryonday** [comment]
You're welcome! Super awesome plugin and happy to contribute!
