### ISSUE TITLE
Remove pre-cleaning behavior

### ISSUE THREAD

**Issue by whipit** [commercehub-oss/gradle-avro-plugin#41]
I want the generated class to be written to my existing src folder, instead of the build folder.

For example, if I have a structure like below:
```
app
  /src
      /main
         /java
            /models
                SomePojo.java
        /avro
            AnotherPojoSchema.asvc
```

And I have this build.gradle

```
task generateAvro(type: com.commercehub.gradle.plugin.avro.GenerateAvroJavaTask) {
    source("src/main/avro/AnotherPojoSchema.avsc")
    outputDir = file("src/main/java/models")
}
compileJava.source(generateAvro.outputs)
```

And this AnotherPojoSchema.asvc
```
{
  "namespace": "models",
  "type": "record",
  "name": "AnotherPojo",
  "fields": [
    {"name": "FirstName", "type": "String"},
    {"name": "LastName", "type": "String"}
  ]
}
```

I would like the class AnotherPojo.java to be created under src/main/java/models/.

However, instead what happen is it 

- wipes (rm -rf) out directory src/main/java/models.   This can be quite dangerous as you can lose your work.
- writes generated file under src/main/java/models/**models**/AnotherPojo.java

On the contrary, if you use the avro utility by itself, it does not behave this way.  It will create the AnotherPojo.java file, while preserving any existing source code in the package path.

java -jar ./avro-tools-1.8.2.jar compile schema src/main/avro/AnotherPojoSchema.avsc src/main/java/.

leaves you with

```
app
  /src
      /main
         /java
            /models
                AnotherPojo.java
                SomePojo.java
```

Can this behaviour be changed?

Thanks

Tim

**Comment by davidmc24** [comment]
The upstream compiler has a behavior that it silently refuses to re-generate class files that already exist if the class file is newer than the schema file.  This was intended as a performance optimization, and is not something that is currently possible to disable.

In the case where one of the other schema files that was included by reference in the schema file was changed, this behavior results in the generated classes being out-of-date when schema files that are referenced in other schema files are modified.  The solution was to work around the upstream behavior by adding a cleaning behavior.

For your use-case, I recommend something like this:

```groovy
task generateAvro(type: com.commercehub.gradle.plugin.avro.GenerateAvroJavaTask) {
    source("src/avro")
    outputDir = file("dest/avro")
}
task copyAvro(type: Copy) {
    dependsOn generateAvro
    from "dest/avro"
    into "src/main/java"
}
compileJava.dependsOn copyAvro
```

This still has a separate, dedicated folder for Avro generation, but results in the generated files being present in your existing source folder.

**Comment by whipit** [comment]
Thank you.  I think this will work just fine.   I would recommend changing the behavior so that it is not by default - since you could very easily lose work.  Perhaps be explicit about what you are deleting (i.e. only delete files you are replacing), or make the switch so that deleting is not the default behavior, i.e. you need to opt into it via an option.  

Other than that, this is a very handy plugin!

**Comment by davidmc24** [comment]
Thank you for your feedback.

The upstream Avro compiler may generate many Java files based on a single Avro schema file, and there's no way to know what files it would generate without either running it or parsing the schema files independently.  Thus, I don't think that being explicit about what is being deleted is a viable option.

Adding a configuration setting to disable the pre-cleaning wouldn't make sense, as there isn't a case where it is a recommended approach to disable the pre-cleaning.  Disabling the pre-cleaning results in exposure to risk of inconsistent, incorrect generated files, while the intended usage (a dedicated directory under the buildDir) has little to no downside.

I could take away the ability to configure the output directory of `GenerateAvroJavaTask`, hoping to eliminate potential for human error, but whatever path was chosen, there's still risk of collision, and it could result in incompatibility with particular environments.

The options that make most sense to me are:

* Propose an enhancement to the upstream compiler to remove or allow disabling the "only compile newer schema files" performance enhancement.  If accepted, this would eventually allow removing the pre-cleaning from this plugin.
* Update the README for this plugin to warn about the pre-cleaning behavior.
* Update the plugin to refuse to refuse to run when the `outputDir` is not within the project's `buildDir`, indicating a potentially dangerous configuration.  Possible variant would be to log a warning, but by the time you would see the warning, you may have already lost data.

I'll pursue all of these three options.

**Comment by davidmc24** [comment]
Before writing to the avro-dev mailing list to request a feature change, I wanted to have a clear example of what scenario we were talking about improving.  While I'm certain I at one point hit a problem which pre-cleaning solved, I can't recall it clearly enough to write a test to reproduce it.  Upon deeper thought, the only cases I'm coming up with where the pre-cleaning would result in a behavior difference would be:

* A schema file is removed (or a section of a multi-type schema file) resulting in an orphaned class file in the `outputDir`.  This is a situation where the user should manually clean.
* You build, and then perform a version control operation which switches your schema files for older versions (which are then out-of-sync with the build output).  This is a situation where the user should manually clean.

Having multiple schema files defining the same type may result in inconsistent behavior, but that is still inconsistent regardless of whether pre-cleaning is performed.

Thus, I'll be removing pre-cleaning entirely until/unless a clearer use-case for it emerges.

**Comment by whipit** [comment]
Thanks, that makes a lot of sense.   The onus is on the developer to ensure correct schema usage.  It's better to have it fail, cause there may be other implications as you well stated.
