### ISSUE TITLE
Support for validation of default values in schema

### ISSUE THREAD

**Issue by rafal-glowinski** [commercehub-oss/gradle-avro-plugin#42]
Avro's `Schema.Parser` supports validation of default values. It is enough to call: `parser.setValidateDefaults(true)` and when the parser encounters such invalid default an exception is thrown with a message: 

> Invalid default for field name: null not a "string"

It would be really nice to have an additional option for the plugin that allows enabling this validation.

I think that something like this would be just fine (with the default set to 'false' - to remain backward compatible):

```groovy
avro {
    validateDefaults = true
}
```

**Comment by davidmc24** [comment]
Thanks for the issue and pull request. Other than retaining backwards compatibility, is there any reason to not want this validation on?  Maybe a performance penalty (and if so, any idea how much)?  Is there any case where turning this option on would result in a valid schema no longer being usable?

**Comment by rafal-glowinski** [comment]
Looking at the code of `Schema.Parser` I don't think there should be any considerable performance cost to this validation. The schema is already parsed and it is in memory, so it would be just calling few additional methods on fields that have defaults.

Why not make it default = true? Well, I have always a big fan of backward compatibility so there is that. Also, AVRO will generate classes for a schema that has invalid defaults, so it is possible that schema considered by someone as valid will turn out not to be valid at all. 

When classes for such invalid schema are generated, it will still be possible to use them as long, as Avro does not have to assign a default value to a field. When the generated builder is used and no user value will be provided to such field, then builder will fail with an exception (`org.apache.avro.AvroTypeException: Non-string default value for string: null`).

**Comment by rafal-glowinski** [comment]
@davidmc24 so, what now? :)

**Comment by davidmc24** [comment]
Sorry for the delay. Things are pretty on my end. While I place value on backwards compatibility, I also value a simple user experience, and part of that is minimizing configuration. Thus, I’m torn between accepting the pull request as-is, or requesting that it be changed to be always-on and eliminate the configuration.

**Comment by davidmc24** [comment]
If I accept it with configurability now, I’ll almost certainly want to eliminate the configurability in the next release that breaks compatibility.

**Comment by rafal-glowinski** [comment]
I think that is the best thing to do. At least if you are planning on a release that breaks compatibility.

**Comment by davidmc24** [comment]
That works. Please make that change. I expect I’ll be able to merge this and push out a release early next week.

**Comment by rafal-glowinski** [comment]
Done. I also added a bit of info of this validation to changelog.

**Comment by davidmc24** [comment]
Great!  Thanks again.  Looks good to merge.  I'll schedule time to work through the release next week.

**Comment by davidmc24** [comment]
Included in release of 0.14.0.  Thanks again!
