### ISSUE TITLE
Java files are not generated from Avro schema in Android project

### ISSUE THREAD

**Issue by rohitramkumar308** [commercehub-oss/gradle-avro-plugin#45]
I have followed all the setup instructions but this plugin is not working in my Android Project.
 I tried to add `com.commercehub.gradle.plugin.avro` plugin but I get a build error:

> Error:The 'java' plugin has been applied, but it is not compatible with the Android plugins.

Hence I added the `com.commercehub.gradle.plugin.avro-base` plugin. I put my `.avsc` files in `src/avro` folder but nothing seems to be working. Please help.

**Comment by davidmc24** [comment]
I’m sorry to hear you’re having difficulty. It’s possible that this plugin isn’t compatible with Android projects. I’m busy today, but should be able to take a look tomorrow.

**Comment by davidmc24** [comment]
I can confirm that the convention-oriented plugin (com.commercehub.gradle.plugin.avro) is definitely not compatible with Android projects, as it depends on capabilities provided by the Java plugin that the Android plugin isn't compatible with.

It should be possible to apply the base plugin (com.commercehub.gradle.plugin.avro-base) as documented in the "Alternate Usage" section of the README file.  Just ignore the parts about applying the Java plugin and hooking up the compileJava task.  I'm afraid I don't have any notable Android experience and don't know the appropriate way to hook the Avro-generated Java source files into the rest of the Android build process.

**Comment by rohitramkumar308** [comment]
Awesome. Thank you very much @davidmc24. This works fine. Also just for information the way to hookup avro models is to add the following dependency to the `build.gradle` file: 
`implementation "org.apache.avro:avro:1.8.2"`

**Comment by KwanLye** [comment]
@rohitramkumar308 would you please share the example how to use the base plugin (com.commercehub.gradle.plugin.avro-base)? Thanks!

**Comment by pranshu1701** [comment]
@rohitramkumar308 Can you please share a sample code for this?
@davidmc24 Not able to use it in android

**Comment by Snipe3000** [comment]
I've also been trying to get avro to run in android using `id "com.commercehub.gradle.plugin.avro-base" version "0.99.99"` . Whenever I build, I get this error:
`Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform avro-1.10.1.jar (org.apache.avro:avro:1.10.1) to match attributes {artifactType=android-dex, dexing-enable-desugaring=true, dexing-incremental-transform=false, dexing-is-debuggable=true, dexing-min-sdk=16, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: C:\Users\x.van.ferguson\.gradle\caches\transforms-2\files-2.1\83af2d166561fd58ea0eebebc920f350\jetified-avro-1.10.1.jar.
         > Error while dexing.`

Has anyone ran into anything like this?

**Comment by davidmc24** [comment]
@Snipe3000 Note that the plugin version you're using is out-of-date. Please upgrade to 1.0.0.
