### ISSUE TITLE
why delete target all files?

### ISSUE THREAD

**Issue by libra1010** [commercehub-oss/gradle-avro-plugin#51]
why delete target all files?
set target is src/main/java

but .... 
java Folder
all codes ....
OMG

**Comment by davidmc24** [comment]
There was a point where this behavior was necessary to work around an Avro compiler behavior where it doesn't compile if the target file already exists.  This is no longer the case, and the deletion behavior has been removed in version 0.13.0.  Version 0.13.0 and later no longer pre-clean the target directory.

**Comment by StuAtGit** [comment]
Running version 0.9.2:
```
    compile group: 'org.apache.avro', name: 'avro', version: '1.9.2'
```
Configured it to put the source in the normal location:
```
def generateProtocol = tasks.register("generateProtocol", GenerateAvroProtocolTask) {
    source("src/main/avro")
    include("*.avdl")
    outputDir = file("src/main/avro/protocols")
}

def generateJava = tasks.register("generateJava", GenerateAvroJavaTask) {
    source("src/main/avro/protocols")
    include("*.avpr")
    outputDir = file("src/main/java")
}
```

Deleted my entire source code base. 
It should warn before it does something like that. Srsly. Flames. On the Side of Face 🔥

**Comment by davidmc24** [comment]
This problem was fixed ages ago. Upgrade and you won’t run into old bugs.
