### ISSUE TITLE
Unnecessary IntelliJ directories get created when configuring outputDir

### ISSUE THREAD

**Issue by xkrogen** [commercehub-oss/gradle-avro-plugin#52]
I noticed that when I specify a custom `outputDir` for a `GenerateAvroJavaTask`, the plugin still creates `generated-main-avro-java` and `generated-test-avro-java` when I run the `idea` task.

I believe this comes from the following code within `AvroPlugin`:
```java
                final File mainGeneratedOutputDir = getGeneratedOutputDir(project, mainSourceSet, JAVA_EXTENSION);
                final File testGeneratedOutputDir = getGeneratedOutputDir(project, testSourceSet, JAVA_EXTENSION);
                project.getTasks().withType(GenerateIdeaModule.class).all(new Action<GenerateIdeaModule>() {
                    @Override
                    public void execute(GenerateIdeaModule generateIdeaModule) {
                        generateIdeaModule.doFirst(new Action<Task>() {
                            @Override
                            public void execute(Task task) {
                                project.mkdir(mainGeneratedOutputDir);
                                project.mkdir(testGeneratedOutputDir);
                            }
                        });
                    }
                });
```
Here, the output of the `getGeneratedOutputDir` method is used directly, whereas other places that this method is used (e.g. in `configureJavaGenerationTask`), a convention mapping is instead used. My understanding on this is not very deep but I believe that the convention mapping will respect when I override the value in my task, whereas the above snippet clearly will not.

I'm not entirely sure why, but these extra directories cause IntelliJ to complain like:

> Source root "/path/to/project/build/subproject/generated-main-avro-java" cannot be defined
> in module "subproject" because it belongs to content of nested module "project".

Manually deleting the directories fixes the problem, but they shouldn't be created in the first place.

**Comment by davidmc24** [comment]
Thank you for the report, @xkrogen.  I believe I've pushed a commit that should fix this.  If it looks like the new test appropriately captures the problem you encountered, I'll roll this into a release.

**Comment by xkrogen** [comment]
Wow, that was an incredible turnaround time. The fix LGTM. Thanks @davidmc24 !

**Comment by davidmc24** [comment]
Thanks, I try to be responsive.

**Comment by xkrogen** [comment]
Hey @davidmc24 , I just tried this using version 0.14.2 on Gradle 4.6 and the directories were still generated. Here's a minimal `build.gradle` which reproduces the problem:
```
apply plugin: 'java'
apply plugin: 'idea'

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "com.commercehub.gradle.plugin:gradle-avro-plugin:0.14.2"
    }
}
apply plugin: "com.commercehub.gradle.plugin.avro"

task generateJava(type: com.commercehub.gradle.plugin.avro.GenerateAvroJavaTask) {
  source("src/main/resources/schema")
  outputDir = file("src/generated/java")
}
```
```
> ./gradlew idea
BUILD SUCCESSFUL in 0s
> ls build
generated-main-avro-java generated-test-avro-java
```
Any thoughts on what might be wrong?

**Comment by davidmc24** [comment]
So, the way the logic works now, for each task of type `com.commercehub.gradle.plugin.avro.GenerateAvroJavaTask`, the plugin adds an action to create the output directory.  In your example, you're adding an additional task that meets this criteria, without re-configuring the existing tasks `generateAvroJava` and `generateTestAvroJava` (as demonstrated in the test [here](https://github.com/commercehub-oss/gradle-avro-plugin/blob/master/src/test/groovy/com/commercehub/gradle/plugin/avro/IntellijFunctionalSpec.groovy#L61)).  Thus, it will create the new output directory `src/generated/java` as well as the defaults.

**Comment by xkrogen** [comment]
Ah, understood, thank you for the clarification!

**Comment by smitamoonka** [comment]
> Hi, @xkrogen. The way the logic works now, for each task of type `com.commercehub.gradle.plugin.avro.GenerateAvroJavaTask`, the plugin adds an action to create the output directory. In your example, you're adding an additional task that meets this criteria, without re-configuring the existing tasks `generateAvroJava` and `generateTestAvroJava` (as demonstrated in the test [here](https://github.com/commercehub-oss/gradle-avro-plugin/blob/master/src/test/groovy/com/commercehub/gradle/plugin/avro/IntellijFunctionalSpec.groovy#L61)). Thus, it will create the new output directory `src/generated/java` as well as the defaults.

This link is not working, please share.
