### ISSUE TITLE
`validateDefaults` is gone, but still in the README

### ISSUE THREAD

**Issue by rocketraman** [commercehub-oss/gradle-avro-plugin#55]
The README still mentions `validateDefaults`, even though the code no longer seems to support it.

**Comment by davidmc24** [comment]
As far as I can see, the code supports it, both in implementation and tests

https://github.com/commercehub-oss/gradle-avro-plugin/search?q=validateDefaults&unscoped_q=validateDefaults

What behavior are you seeing?

**Comment by davidmc24** [comment]
@rocketraman 

I just tested again, and it looks like it's working for me.  Here's a minimal sample project demonstrating its usage: https://gist.github.com/davidmc24/98faf1c41ee0e8725198eaafdc61064e

If that example doesn't give you what you need to get it working, could you share an example project that demonstrates the behavior you're seeing?  My guess is that the most likely problem is that you're on a version prior to 0.14.0.

**Comment by rocketraman** [comment]
@davidmc24  Indeed I am on 0.9.1... note I had trouble finding the version number when I started... the README in this project just lists $VERSION (is that a bug or intentional?), so I went to the gradle plugin registry to get the version #, which still uses 0.9.1 (https://plugins.gradle.org/plugin/com.commercehub.gradle.plugin.avro).

Thanks for your help.

**Comment by davidmc24** [comment]
This project doesn’t publish new versions to the Gradle plugin portal
anymore due to their continued lack of download stats reporting.  Thus, the
versions there are out of date.

As noted in the readme, the recommended way to select a version is based on
the list in
https://github.com/commercehub-oss/gradle-avro-plugin/blob/master/CHANGES.md

**Comment by rocketraman** [comment]
Thanks!
