### ISSUE TITLE
Add support for generating schema files from protocol files

### ISSUE THREAD

**Issue by scottadav** [commercehub-oss/gradle-avro-plugin#56]
Would it be possible to generate schema (avsc) files from protocol files (avdl)? Some integrations only support schemas but not protocols.

This can currently be done on the command line by running avro-tools (`java -jar avro-tools-1.8.2.jar idl2schemata protocol.avdl .`), but it would be nice to have it inside the plugin.

**Comment by davidmc24** [comment]
I believe that the plugin already supports this, though the README may not call it out clearly enough.  If you use the "com.commercehub.gradle.plugin.avro" plugin, files matching *.avdl in registered source directories (such as `src/main/avro`) will be handled by [GenerateAvroProtocolTask](https://github.com/commercehub-oss/gradle-avro-plugin/blob/master/src/main/java/com/commercehub/gradle/plugin/avro/GenerateAvroProtocolTask.java), which generates a schema file from the protocol file.

Test demonstrating the functionality:

https://github.com/commercehub-oss/gradle-avro-plugin/blob/master/src/test/groovy/com/commercehub/gradle/plugin/avro/AvroPluginFunctionalSpec.groovy#L52

**Comment by scottadav** [comment]
Java generation is working perfectly.

However, I'm trying to generate avdl -> avsc, in order to feed the avsc files to the Confluent Schema Registry, a tool which checks Avro schemas for incompatibilities. It's a separate step of our build process that verifies all schema changes we make are both forward and backward compatible with the previous schema version.

**Comment by davidmc24** [comment]
Ah, sorry.  I misunderstood the request.  The `GenerateAvroProtocolTask` currently does avdl -> avpr conversion, while you're looking for avdl -> avsc.

I'm open to a task for this being included in the plugin, but don't think that it would be something that is applied to projects by default (that is, you'd need to include a definition of the task based on the task type in your build file).  For consistency with the other tasks, I'd want it to use the `avro-compiler` Java API rather than the `avro-tools` command-line tool.  I'm willing to put this together, but it may take me a couple weeks before I get around to it.  Alternatively, I'm open to a pull request.

**Comment by davidmc24** [comment]
@scottadav I think I've added appropriate support to meet your use-case.  Please take a look, and if it makes sense to you, I'll cut a release.

**Comment by scottadav** [comment]
Sorry about the slow response. Yes, I was able to get it working with our build.

Thanks for your help!!!

FYI, it only works with AVPR and not AVDL. There is a test step named `can generate json schema files from IDL` but the test itself actually uses AVPR as the source. That turned out not to be a problem, because we were already converting our AVDL->AVPR using the standard tasks from the plugin.

I can confirm that the generated AVSC files work with the Avro Schema Registry tool.

**Comment by davidmc24** [comment]
@scottadav Yes, the new task only supports AVPR -> AVSC, as the plugin already supplies a task for AVDL -> AVPR.  My thinking was that it was reasonable to require a two-step process for AVDL -> AVPR.  The test you mentioned uses a source AVPR file, and demonstrates using the two tasks together to provide an end-to-end AVDL -> AVSC process.

**Comment by cargillchantry** [comment]
I have tried using this, but I notice that the schema files differ from the schema stored within the java classes (for example they are missing fields like avro.java.string under type). Is this intended? If they matched it would solve a bit of an annoying problem I am having with generated dtos being rejected by the schema registry.

**Comment by davidmc24** [comment]
@cargillchantry Please submit as a new issue, with a more detailed explanation of the problem you’re encountering.

**Comment by ykcai** [comment]
Is there an example of this somewhere? I keep getting no source when i try to run this task in gradle..

**Comment by davidmc24** [comment]
@ykcai Please do not revive old issues.  If needed, create new issues and reference the previous one discussing a topic.  Assuming the "example of this" that you're looking for is AVPR -> AVSC generation, it is documented here: https://github.com/davidmc24/gradle-avro-plugin#generating-schema-files.

Locking this ticket for further discussion.
