### ISSUE TITLE
Boolean configuration cannot be set with boolean values from Kotlin DSL

### ISSUE THREAD

**Issue by mykolapolonskyi** [commercehub-oss/gradle-avro-plugin#60]
![image](https://user-images.githubusercontent.com/7451751/45159206-d7767e80-b1ee-11e8-9cb8-4426cddd7b9c.png)

in use of gradle kotlin dsl - createSetter filed can be configured as dsl if java class method will be under naming convention/with correct contract. Contract now is: 

> com.commercehub.gradle.plugin.avro.DefaultAvroExtension#setCreateSetters(String createSetters) 

Overload 

 > com.commercehub.gradle.plugin.avro.DefaultAvroExtension#setCreateSetters(boolean createSetters)

can be very useful.

p.s. I found usage kotlin for gradle/maven plugin development very useful, of course those plugins was much smaller but - can say that if u have a minute take a look =)

**Comment by davidmc24** [comment]
Thanks for the bug report.  I don't currently have any test coverage for usage of the plugin from the Kotlin DSL... and am not going to add it just now, but will add it to the backlog as a future idea.  Working on a fix for this issue.

**Comment by davidmc24** [comment]
Also applies to validateDefaults

**Comment by davidmc24** [comment]
After the fix, it will work from Kotlin DSL, but will require referencing the properties using the getter name.  For example, instead of `createSetters = false`, one would use `isCreateSetters = false`.

**Comment by davidmc24** [comment]
Fix included in version 0.15.1.
