### ISSUE TITLE
GenerateAvroTask does not work

### ISSUE THREAD

**Issue by NavyaGarg** [commercehub-oss/gradle-avro-plugin#62]
Hello,
I am using avro gradle plugin to generate java classes.

task generateAvro(type: com.commercehub.gradle.plugin.avro.GenerateAvroJavaTask) {
source("${buildDir}/src/main/avro")
outputDir = file("dest/avro")
outputs.upToDateWhen { false }
}

I am getting the following error

A problem occured while evaluating project 'project_name'
>org.gradle.api.internal.TaskOutputsInternal.dir(Ljava/lang/Object:)Lorg/gradle/api/taks/TasksOutputFilePropertyBuilder:;

The build is failing with this error.  Can anybody suggest if i am missing something.

**Comment by davidmc24** [comment]
That task definition appears to work for me.  More information would be needed in order to diagnose the problem, such as a standalone project that demonstrates the issue.  Alternatively, you could consider seeking help on the Gradle project's forums.

https://discuss.gradle.org/c/help-discuss

**Comment by NavyaGarg** [comment]
I think its failing because of the gradle version as it worked for me as well when I used the gradle version - 4.10.2

But I actually want to use it in a project having gradle version 2.12. Is there anything I need to change in that case.

**Comment by davidmc24** [comment]
https://github.com/commercehub-oss/gradle-avro-plugin/blob/master/README.md documents the versions of Gradle supported.  Version 2.12 is outside the range that will work with the latest version of the plugin.
