### ISSUE TITLE
Use full class name for java.lang.Exception

### ISSUE THREAD

**Issue by newton449** [commercehub-oss/gradle-avro-plugin#67]
Hi, could you use full class name for java.lang.Exception?

For example, in the generated codes below:

> 

    @Override
    public PageInstance build() {
      try {
        PageInstance record = new PageInstance();
        // ...
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }

replace `} catch (Exception e) {` with `} catch (java.lang.Exception e) {`

Not a big issue, but we have an Exception class (which is not a Java throwable) in the same package of PageInstance. 

Thanks,
newton449

**Comment by davidmc24** [comment]
The class-generation templates aren't currently part of this project, and this isn't a common enough case that I'm going to pull them in to support this.  A few options for you:

* Upgrade to a plugin version that uses Avro 1.8.2 (0.11.0 or later), as they appear to have changed this as a response to https://issues.apache.org/jira/browse/AVRO-1901
* Leverage the plugin's support for custom templates to specify your own templates that use fully qualified class names for `java.lang.Exception`; see https://github.com/commercehub-oss/gradle-avro-plugin#templatedirectory
* Rename your class to something other than `Exception`, as it's inviting conflicts with a default-import SDK class

**Comment by newton449** [comment]
Thanks for your quick response. Very helpful!
