### ISSUE TITLE
Source code generator is not working properly with default values

### ISSUE THREAD

**Issue by adam-arold** [commercehub-oss/gradle-avro-plugin#68]
I have an AVRO schema which **works** with Maven, but with the Gradle AVRO plugin I get this error:

```
> Could not compile schema definition files:
  * src/main/resources/schema/avro/SomeFile.avsc: "map" is not a defined name. The type of the "enabled" field must be a defined name or a {"type": ...} expression.
```

This is how `enabled` looks like in my `.avsc` file (I only copied the relevant parts):

```
{
  "name": "SomeType",
  "type": "record",
  "fields": [
    {
      "name": "somename",
      "type": {
        "type": "record",
        "name": "SomeName",
        "fields": [
          {
            "name": "enabled",
            "type": {
              "type": "map",
              "values": "boolean"
            },
            "default": "{}"
          },
        ]
      }
    }
  ]
}
```

What could be the problem?

**Comment by davidmc24** [comment]
I'm not sure what to tell you.  This schema file appears to work in my test project when I eliminate the stray comma after the inner fields declaration.  What version of the plugin, Gradle, and Java are you using?

```
{
  "name": "SomeType",
  "type": "record",
  "fields": [
    {
      "name": "somename",
      "type": {
        "type": "record",
        "name": "SomeName",
        "fields": [
          {
            "name": "enabled",
            "type": {
              "type": "map",
              "values": "boolean"
            },
            "default": "{}"
          }
        ]
      }
    }
  ]
}
```

**Comment by adam-arold** [comment]
Sorry the stray comma is there because there are multiple fields after it I just removed them.
I'm using Kotlin (shouldn't be relevant), Gradle 4.6 and 
```
"com.commercehub.gradle.plugin:gradle-avro-plugin:0.16.0"
```

Note that I use the `com.commercehub.gradle.plugin.avro-base` plugin as was suggested in the documentation because I want to set the source/target directories:

```
task generateAvro(type: GenerateAvroJavaTask) {
    createSetters = true
    fieldVisibility = "PRIVATE"
    outputCharacterEncoding = "UTF-8"
    stringType = "String"
    validateDefaults = true
    source("src/main/resources/schema/avro")
    outputDir = file(generatedSourceDir)
}

compileJava.source(generateAvro.outputs)
```

**Comment by davidmc24** [comment]
No problem with the stray comma, totally understandable.

When I update my test project to be more similar to that, I get an error `Invalid default for field enabled: "{}" not a {"type":"map","values":"boolean"}`, which is related to the `validateDefaults` setting being enabled.  I think this may be a feature that the Maven plugin doesn't have, so that would explain a different behavior.

I think it's possible that the problem is that a default empty map should be an empty JSON object, rather than a quoted string.

```
{
  "name": "SomeType",
  "type": "record",
  "fields": [
    {
      "name": "somename",
      "type": {
        "type": "record",
        "name": "SomeName",
        "fields": [
          {
            "name": "enabled",
            "type": {
              "type": "map",
              "values": "boolean"
            },
            "default": {}
          }
        ]
      }
    }
  ]
}
```

**Comment by adam-arold** [comment]
Great thanks, this was the solution! Should I close this?

**Comment by davidmc24** [comment]
I'm glad I could be of help.  I'll close out the issue.
