### ISSUE TITLE
time logical types default java date package

### ISSUE THREAD

**Issue by cgraving** [commercehub-oss/gradle-avro-plugin#74]
When using the time logical types the resulting java uses joda. Is there a means to set the desired dates to use? Joda versus java, etc? If I am not mistaken as of java 8 java=joda, but don't need to add the dependencies, etc. Would love to be able to do something like strings where I can change the resulting java types.

**Comment by davidmc24** [comment]
I believe that this configuration is something that is being added in Avro 1.9.0.  Please see #69

**Comment by cgraving** [comment]
Sounds good. Will add to my list of things I am waiting on 1.9 for. Hopefully soon! Thanks!
