### ISSUE TITLE
Generated classes are using TimeConversion methods that are not available in 1.9.0 of apache avro

### ISSUE THREAD

**Issue by smitp33** [commercehub-oss/gradle-avro-plugin#76]
Using a avsc file that references the logicalType of "timestamp-millis"
```
{
      "name": "timestamp",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      },
      "doc": "The timestamp for when the event was created"
}
```
The generated code using apache avro 1.9.0 produces the following:

```
protected static final org.apache.avro.data.TimeConversions.TimeConversion TIME_CONVERSION = new org.apache.avro.data.TimeConversions.TimeConversion();
  protected static final org.apache.avro.data.TimeConversions.TimestampConversion TIMESTAMP_CONVERSION = new org.apache.avro.data.TimeConversions.TimestampConversion();
```
TimeConversion & TimestampConversion are not available in version 1.9.0. They seem to have been replaced with TimestampMillisConversion

If I use avro 1.8.2 then these methods are available.

**Comment by davidmc24** [comment]
I'm sorry to hear that you're having problems.  I have attempted to reproduce this failure, and thus far have been unable to reproduce it.  If you could provide a full project that demonstrates the failure, I may be better able to help.

Please see attached project which, at least for me, appears to demonstrate it working.

* `src/main/avro/UsesTimestamp.avsc` contains a timestamp field based on your example
* Running `./gradlew clean build` generates and compiles the Java classes based on the schema file without error
* `build/generated-main-avro-java/UsesTimestamp.java` contains references to `org.apache.avro.data.TimeConversions.TimestampMillisConversion()`, but not to `org.apache.avro.data.TimeConversions.TimeConversion` or `org.apache.avro.data.TimeConversions.TimestampConversion`

[gradle-avro-plugin-ts-repro.tar.gz](https://github.com/commercehub-oss/gradle-avro-plugin/files/3212287/gradle-avro-plugin-ts-repro.tar.gz)

My guess is that either you are using the `templateDirectory` feature to specify custom templates (in which case you'll need to update them), or you have a mismatch between the version of the plugin you're running and the version of Avro that you're attempting to compile using.

Comparing the output of `./gradlew buildEnvironment` and `./gradlew dependencies --configuration compileClasspath` should help to diagnose the latter case.

**Comment by smitp33** [comment]
Thanks for the very rapid response. I will take a look at what you sent and also see if I can recreate. I am not aware that we are using that feature that you mentioned, but will take a look 😀

**Comment by smitp33** [comment]
So this is the output of the second command for the relevant section ....
```
+--- com.commercehub.gradle.plugin:gradle-avro-plugin:0.16.0
|    \--- org.apache.avro:avro-compiler:1.8.2
|         +--- org.apache.avro:avro:1.8.2 -> 1.9.0
|         |    +--- com.fasterxml.jackson.core:jackson-core:2.9.8
|         |    +--- com.fasterxml.jackson.core:jackson-databind:2.9.8 (*)
|         |    +--- org.apache.commons:commons-compress:1.18
|         |    \--- org.slf4j:slf4j-api:1.7.25 -> 1.7.26
|         +--- commons-lang:commons-lang:2.6
|         +--- org.apache.velocity:velocity:1.7
|         |    +--- commons-collections:commons-collections:3.2.1
|         |    \--- commons-lang:commons-lang:2.4 -> 2.6
|         +--- org.codehaus.jackson:jackson-core-asl:1.9.13
|         +--- org.codehaus.jackson:jackson-mapper-asl:1.9.13
|         |    \--- org.codehaus.jackson:jackson-core-asl:1.9.13
|         +--- joda-time:joda-time:2.7
|         \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.26
+--- org.apache.avro:avro:1.9.0 (*)
```
So am I interpreting this correctly - the 0.16.0 plugin currently depends on 1.8.2 and therefore trying to use 1.9.0 instead will not work - I noticed that your sample was using 0.17.0 so using that seems to sort this issue out ...

**Comment by davidmc24** [comment]
Yep, if you want 1.9.0 support, please use plugin version 0.17.0.  Glad to hear that things appear to be working for you now.  Cheers!

**Comment by dallas-gantamahender** [comment]
Hello @davidmc24, I have the similar issue where I updated the avro jar from 1.8.2 to 1.9.2, now I am getting the classnotfound exception for the TimeConversions$TimeConversion. I am using maven and avro-maven-plugin is also same as the avro jar. I am not sure what is the issue, could you please suggest here?

Exception:
Caused by: java.lang.ClassNotFoundException: org.apache.avro.data.TimeConversions$TimeConversion

**Comment by davidmc24** [comment]
If you're using Maven, please submit your support request to the Apache Avro project, as this project only deals with a Gradle plugin.
