### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ayush-finix** [commercehub-oss/gradle-avro-plugin#77]
Are there any plans to push this to the default gradle plugins repo? I notice the latest version is still 0.9.1 at https://plugins.gradle.org/plugin/com.commercehub.gradle.plugin.avro

**Comment by davidmc24** [comment]
No, not unless/until the Gradle Plugin Portal provides a way to view usage statistics.

**Comment by scprek** [comment]
linking disc here https://discuss.gradle.org/t/plugin-portal-download-statistics/11609
