### ISSUE TITLE
Cannot access `org.apache.avro.specific.SpecificRecordBase`

### ISSUE THREAD

**Issue by tianhao-au** [commercehub-oss/gradle-avro-plugin#79]
It's may not an issue but more about question.

If I have this plugin in the same project as I used there is totally fine without any problem.

But when I separate the project having this plugin (publish to artifactory) and the project will use the generated classes I have some issue when I do:
`DemoClass.newBuilder().build();`
I have following compile errors:
`Cannot access `org.apache.avro.specific.SpecificRecordBase`

Not sure what configs I am missing?

Thanks.

**Comment by davidmc24** [comment]
This doesn't sound like something specific to the gradle plugin, as at the point that the classes have been generated, the plugin isn't doing anything.

Classes generated by Avro's "compiler" have dependencies on the Avro libraries.  If you get class not found or access exceptions related to Avro classes, it likely means that either the Avro libraries are not on your classpath, are an incompatible version, or you have your JVM configured to prevent access.
