### ISSUE TITLE
Support for custom conversions

### ISSUE THREAD

**Issue by davidmc24** [commercehub-oss/gradle-avro-plugin#80]
I know this issue was closed and it addresses the Java 8 dates. I'm trying to figure out how to register a custom conversion for OffsetDateTime that currently isn't supported. I created a conversion class:

`public class OffsetDateTimeConversion extends Conversion<OffsetDateTime>`

with logicalTypeName = 'offset-date-time' that implements `toCharSequence` and 'fromCharSequence` so I can convert to/from ISO 8601 date/time string with timezone offset.

What I can't figure out is how to register the "offset-date-time" logical type. Debugging the maven-plugin, I see when it parses my schema that contains a field with a custom logical type:
`
"name": "createDateTime",
            "type": {
                "type": "string",
                "logicalType": "offset-date-time"
            }
`
it tries to set the field schema's logicalType property and since it isn't a built-in one ("timestamp-millis", "decimal", "date", etc) it looks for it in the REGISTERED_TYPES map but it doesn't exist.

The result is my generated class doesn't contain the conversion for my custom logical type,

The code I need to execute to register the logical type is:
`
LogicalTypes.register(getLogicalTypeName(), schema -> new OffsetDateTimeLogicalType());
`

Without modifying plugin code, I don't see a why to register my logical type before the schema parses. Just wondering if you have any experience/luck with this. Thanks!

_Originally posted by @tyocum17 in https://github.com/commercehub-oss/gradle-avro-plugin/issues/54#issuecomment-517290860_

**Comment by davidmc24** [comment]
To answer your direct question, I don't have experience with this, and haven't tried.

I don't think that this is something that can currently be done with the plugin as-is, as it would require custom code to be run on the compiler classes prior to Avro compilation, and the plugin currently doesn't expose a hook to do so.

That said, we can certainly discuss potential workarounds and feature requests that could enable this.

The workaround mentioned in #54 would still be viable, though a bit cumbersome; effectively, put together a patched version of Avro that includes your custom type by default, and tell the plugin to use it at build time.

In terms of new features for the plugin, we could go a few directions.  Just brainstorming here:

* Add some form of lightweight plugin mechanism, so that adding a jar to the plugin classpath can cause new logical types to be automatically registered, probably using [ServiceLoader](https://docs.oracle.com/javase/7/docs/api/java/util/ServiceLoader.html).  This might not age well as the plugins DSL (`plugins { id 'whatever' }` becomes dominant and most people aren't familiar with the `buildscript` block.
* Some pattern where, instead of using the Avro plugin directly, you instead use it as a library that you wrap in your own plugin.  This might require adding new methods to the `Task` implementation to allow customizing the compilers, for example.  This approach would give the "wrapper" plugin full control over the classpath, allowing adding both new dependent libraries and new classes.  This requires more user sophistication than some approaches... but I suppose it's from the starting point of "user wants to do something that requires custom code".
* Maybe some way to define a closure in the build file that would be run as part of the compile task?  My guess is that in many cases this might still require defining buildscript dependencies (though maybe yours wouldn't, as it's a JDK standard class once you're at an adequate version).

The task methods needed to support build file closure customization might be the same as needed to allow wrapper plugins.  Maybe a signature something like this in `GenerateAvroJavaTask`:

```java
/**
 * Sets the function that will be used to customize the compiler used for customization.
 * By default, the identity function will be used.
 *
 * @param customizer the customizer configured by the plugin
 * @return the customizer to use for compilation
 */
void setCompilerCustomizer(Function<SpecificCompiler, SpecificCompiler> compilerCustomizer) {
    this.compilerCustomizer = compilerCustomizer;
}
```

Then we'd modify `compile(Protocol protocol, File sourceFile)` and `compile(Schema schema, File sourceFile)` to use the `compilerCustomizer`.

https://github.com/commercehub-oss/gradle-avro-plugin/blob/master/src/main/java/com/commercehub/gradle/plugin/avro/GenerateAvroJavaTask.java

Any thoughts on this approach (or any others, for that matter)?

**Comment by aheiss1** [comment]
Admittedly out of the loop here, though as soon we see a customize pushed
to anything need to wonder what behavior require a tweak. Why would native
compiler not work in first place?

There is this plugin limitation artificially and/or importantly put in
place for reasons, though this is either wrong or too blatant?

All I got for now.

Alex

**Comment by davidmc24** [comment]
@aheiss1 The fundamental purpose of this plugin is to ease the use of the Avro `SpecificCompiler` from Gradle to produce Java classes based on Avro schema definitions (in various formats).  As such, all of the out-of-the-box configuration settings that `SpecificCompiler` provides are made easily accessible via plugin configuration options.

That said, there are certain assumptions that `SpecificCompiler` makes beyond its direct configuration that need to be adjusted to handle certain situations.  For example, adjusting the source file output requires changing the templates that are loaded by the compiler on the classpath.  Changing the handling of logical types requires adjusting the static state of `LogicalTypes`.  These are features that the `avro-tools` command-line tool doesn't provide, but which are still useful in certain advanced situations.

**Comment by aheiss1** [comment]
This is wonderful setup David, I do appreciate how that was laid out.
Seems to be consistent and concise with all else here.  Red flag at i think
"  adjusting the static state of LogicalTypes."
Yikes.

Okay i will ponder.  Best of luck this feature. I will do my best to pay
some attention as long as everyone understand I may not have an answer.
Good enough, I'd hope.

Adjusting static state sounds groovyish?

Regards,
Alex

**Comment by aheiss1** [comment]
Guess what I meant on a sorta more precise read, is if you could bucket
those logicaltype s and defer whatever you need until later, idk quick stab
may have been eluded to or yeah actually already established.  I will both
ponder and review.  Be well.

Alex

**Comment by tyocum17** [comment]
Sorry for the confusion. I'm referring to the avro-maven-plugin. In any case, I think a workaround is required I'm just not sure if the suggestions you provided would work in my case (without diving into the maven plugin more).

**Comment by aheiss1** [comment]
All the best, appreciate your understandings and efforts here.

**Comment by davidmc24** [comment]
If I’m understanding right, it sounds like the original post was actually asking for guidance related to the Avro Maven plugin, not anything related to this plugin. As such, closing the ticket. If I am misunderstanding, feel free to re-open it.

**Comment by davidmc24** [comment]
For anyone who may come across this issue, I think I've found an approach to move forward on this (for the gradle plugin, not the maven plugin).  I'll be updating #92 as I make progress.
